import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const licence = `Reference Matrix — an Obsidian plugin
Copyright (c) 2026 SFendorn
SPDX-License-Identifier: MIT`;

const jsBanner = `/*!
${licence}
Bundled dependency licences are collected at the end of this file.

THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const cssBanner = `/*!
${licence}

THIS IS A GENERATED FILE BY ESBUILD
the source is src/styles.css — edit that file, not this one
*/
`;

const prod = process.argv[2] === 'production';

const shared = {
	bundle: true,
	logLevel: 'info',
	minify: prod,
	sourcemap: prod ? false : 'inline',
};

const js = await esbuild.context({
	...shared,
	banner: {
		js: jsBanner,
	},
	entryPoints: ['src/main.ts'],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	treeShaking: true,
	outfile: 'main.js',
});

// Obsidian loads styles.css from the plugin root only, so that path is the
// build output and the annotated source lives in src/ alongside the code.
// legalComments strips even /*! … */, which minify alone would keep.
const css = await esbuild.context({
	...shared,
	banner: {
		css: cssBanner,
	},
	entryPoints: ['src/styles.css'],
	outfile: 'styles.css',
	legalComments: 'none',
});

if (prod) {
	await Promise.all([js.rebuild(), css.rebuild()]);
	process.exit(0);
} else {
	await Promise.all([js.watch(), css.watch()]);
}
